# Generated by Django 2.2.2 on 2019-07-01 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='port',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(65535), django.core.validators.MinValueValidator(1)]),
        ),
    ]
